//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroTrabalhadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABALHADOR
    {
        public int cd_trabalhador { get; set; }
        public string tx_nome_func { get; set; }
        public System.DateTime dt_nasc_func { get; set; }
        public string tx_sexo_func { get; set; }
        public string id_estado_civil_func { get; set; }
        public string tx_end_func { get; set; }
        public Nullable<int> cd_municipio { get; set; }
        public string tx_bairro_func { get; set; }
        public string tx_telefone_func { get; set; }
        public string tx_email_func { get; set; }
        public string tx_cep_func { get; set; }
        public string tx_br_pdh_func { get; set; }
        public string tx_nit_func { get; set; }
        public string nr_ctps_func { get; set; }
        public string nr_serie_ctps_func { get; set; }
        public string tx_uf_ctps_func { get; set; }
        public string tx_cpf_func { get; set; }
        public Nullable<System.DateTime> dt_admissao_func { get; set; }
        public Nullable<System.DateTime> dt_demissao_func { get; set; }
        public System.DateTime dt_cadastro_func { get; set; }
        public Nullable<int> cd_faixa_salarial { get; set; }
        public Nullable<int> cd_escolaridade { get; set; }
        public Nullable<int> cd_raca { get; set; }
        public string tx_rg_func { get; set; }
        public string tx_prontuario { get; set; }
        public string tx_orgao_emissor { get; set; }
        public string tx_telefone_celular { get; set; }
        public Nullable<System.DateTime> dt_falecimento { get; set; }
        public Nullable<System.DateTime> dt_afastamento { get; set; }
        public Nullable<System.DateTime> dt_previsao_retorno { get; set; }
        public Nullable<System.DateTime> dt_retorno_trabalho { get; set; }
    }
}
